# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_2048.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 40, 551, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_24.setLineWidth(5)
        self.label_24.setMidLineWidth(0)
        self.label_24.setText("")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_25.setLineWidth(5)
        self.label_25.setMidLineWidth(0)
        self.label_25.setText("")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_26.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_26.setLineWidth(5)
        self.label_26.setMidLineWidth(0)
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_27.setLineWidth(5)
        self.label_27.setMidLineWidth(0)
        self.label_27.setText("")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_23.setLineWidth(5)
        self.label_23.setMidLineWidth(0)
        self.label_23.setText("")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_19.setLineWidth(5)
        self.label_19.setMidLineWidth(0)
        self.label_19.setText("")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_22.setLineWidth(5)
        self.label_22.setMidLineWidth(0)
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_21.setLineWidth(5)
        self.label_21.setMidLineWidth(0)
        self.label_21.setText("")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_28.setFrameShape(QtWidgets.QFrame.Box)
        self.label_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_28.setLineWidth(5)
        self.label_28.setMidLineWidth(0)
        self.label_28.setText("")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_20.setLineWidth(5)
        self.label_20.setMidLineWidth(0)
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_29.setFrameShape(QtWidgets.QFrame.Box)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_29.setLineWidth(5)
        self.label_29.setMidLineWidth(0)
        self.label_29.setText("")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 2, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_30.setFrameShape(QtWidgets.QFrame.Box)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_30.setLineWidth(5)
        self.label_30.setMidLineWidth(0)
        self.label_30.setText("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 2, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_31.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_31.setFrameShape(QtWidgets.QFrame.Box)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setLineWidth(5)
        self.label_31.setMidLineWidth(0)
        self.label_31.setText("")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_32.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_32.setFrameShape(QtWidgets.QFrame.Box)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_32.setLineWidth(5)
        self.label_32.setMidLineWidth(0)
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_33.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_33.setLineWidth(5)
        self.label_33.setMidLineWidth(0)
        self.label_33.setText("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 3, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_34.setStyleSheet("font: 75 italic 20pt \"UnPilgi\";\n"
"font: 75 14pt \"UnDotum\";")
        self.label_34.setFrameShape(QtWidgets.QFrame.Box)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_34.setLineWidth(5)
        self.label_34.setMidLineWidth(0)
        self.label_34.setText("")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 3, 3, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(340, 620, 251, 41))
        self.lcdNumber.setDigitCount(15)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 627, 51, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(50, 620, 51, 41))
        self.label_18.setObjectName("label_18")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(110, 620, 161, 41))
        self.lcdNumber_2.setDigitCount(10)
        self.lcdNumber_2.setProperty("value", 0.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "Score:"))
        self.label_18.setText(_translate("MainWindow", " Moves:"))

